# Generated by Django 3.1.5 on 2021-02-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='published', max_length=10),
        ),
    ]
